# -*- coding: utf-8 -*-
"""classification_Bayan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYpG9UzEm5aDS-Xn06BwHjRWAuks4cgw

# **Prepare & Explore Dataset**
"""

import numpy as np
import pandas as pd
#read the dataset
iris_data = pd.read_csv('/content/iris_data.csv')

iris_data.head()

iris_data.shape

#split the dataset into train and test
train_data = iris_data.sample(frac=0.8,random_state=0)
test_data = iris_data.drop(train_data.index)
train_data

"""# **Predictors and Target**"""

#split train and test data into predictors and target
train_predictors = train_data[train_data.columns[train_data.columns != 'species']]
train_target = train_data['species']

test_predictors = test_data[test_data.columns[test_data.columns != 'species']]
test_target = test_data['species']

train_predictors

train_target

"""# **Define the neural network architecture**"""

import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras.utils import to_categorical

train_target = to_categorical(train_target)
test_target = to_categorical(test_target)

n = train_predictors.shape[1]

model = keras.Sequential()
model.add(layers.Dense(5, activation='relu',input_shape = (n,) ))
model.add(layers.Dense(5, activation='relu'))
model.add(layers.Dense(3, activation='softmax'))

"""# **Compile the nural net**"""

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy', 'mse']
)

keras.utils.plot_model(model, show_shapes=True, rankdir="LR")

"""# **Fit/ train the nural net**"""

model.fit(train_predictors, train_target, epochs = 500)

"""# **Evaluate the neural net**"""

result = model.evaluate(test_predictors, test_target, verbose=0)
dict(zip(model.metrics_names, result))

"""# **Make predictions / classification for unseen data**"""

#not yet we enhanced the results
prediction = model.predict(test_predictors)
prediction
